# Generated by Django 4.0.1 on 2023-02-23 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ph_num', models.TextField(max_length=10)),
                ('clg_name', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=10)),
                ('brch', models.TextField()),
                ('dp_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('isCordinator', models.BooleanField(default=False)),
            ],
        ),
    ]
