# Generated by Django 4.0.1 on 2023-02-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_bklogs_profile_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bklogs',
            new_name='bklgs',
        ),
    ]
